version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ~/mongodb/database:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=${{ secrets.USER_POSTGRE }}
      - SONARQUBE_JDBC_PASSWORD=${{ secrets.SECRET_POSTGRE }}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macroMateApp
    depends_on:
      - mongodb
    ports:
      - "443:443"
    environment:
      - MONGO_URI=mongodb://admin:example@mongodb:27017/Coordi_f_b
    restart: unless-stopped

volumes:
  mongodb_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data: