version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ~/mongodb/database:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macroMateApp
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:example@mongodb:27017/Coordi_f_b
    restart: unless-stopped

volumes:
  mongodb_data: