version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ~/mongodb/database:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macroMateApp
    depends_on:
      - mongodb
    ports:
      - "443:443"
    environment:
      - MONGO_URI=mongodb://admin:example@mongodb:27017/Coordi_f_b
    restart: unless-stopped

volumes:
  mongodb_data: