export const environment = {
    production: '<GITHUB_PRODUCTION>',
    baseUrl: '<GITHUB_BASE_URL>',
    PORT: '<GITHUB_PORT_URL>',
    MONGODB_URL: '<GITHUB_MONGODB_URL>',
    JWT_SECRET: '<GITHUB_JWT_SECRET>',
    Node_ENV: `<GITHUB_NODE_ENV>`,
    googleClientID: `<GITHUB_GOOGLE_CLIENT_ID>`,
    googleClientSecret: `<GITHUB_GOOGLE_CLIENT_SECRET>`,
    SESSION_SECRET: `<GITHUB_SESSION_SECRET>`,
    CRT_KEY: `<GITHUB_CRT_KEY>`,
    PASSPHRASE: `<GITHUB_PASSPHRASE>`,
    POSTGRE_USER:`<GITHUB_POSTGRE_USER>`,
    POSTGRE_PASS:`<GITHUB_POSTGRE_PASS>`,
    SONAR_HOST_URL: `<GITHUB_SONAR_HOST_URL>`,
    SONARQUBE_TOKEN: `<GITHUB_SONARQUBE_TOKEN>`,
    AZURE_STORAGE_CONNECTION_STRING: `<GITHUB_AZURE_STORAGE_CONNECTION_STRING>`
};
